version: '3'

services:
  app-database:
    image: postgres
    restart: always  
    network_mode: host
    container_name: pg-cnt
    volumes:
      - vol-dir:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=some-user
      - POSTGRES_PASSWORD=some-password

  app-backend:
    image: terezabisharyan/app-server-2:da2ab49
    restart: always
    network_mode: host  
    container_name: back-cnt
    environment:
      - PGUSER=some-user
      - PGPASSOWRD=some-password
      - PGDATABASE=test-db
      - PGHOST=localhost
      - PGPORT=5432

  app-frontend:
    image: terezabisharyan/app-client-2:cc26389
    restart: always  
    network_mode: host  
    container_name: front-cnt



volumes:
  vol-dir:  
